# One-stage build (~46s - 575 MB)
FROM golang:alpine AS builder

# Move to working directory /build
WORKDIR /build

# Copy the go.mod and go.sum files to the /build directory
COPY go.mod go.sum ./
# Install dependencies
RUN go mod download
COPY . .

# Install gcc components (required for sqlite)
RUN apk add gcc musl-dev
# Build the application
RUN CGO_ENABLED=1 GOOS=linux go build -o ../app
RUN CGO_ENABLED=1 GOOS=linux go build db/migrate.go && mv migrate db/
ENTRYPOINT ["/app"]