services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.golang
    env_file:
      - .env.production
    ports:
      - "8080:3000"
    #restart: always
  postgres:
    tty: true
    image: postgres:15.12-alpine
    volumes:
      - ./docker_data/postgresql-15.12:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
